import { PrismaClient } from '@prisma/client';

export async function seedIssues(prisma: PrismaClient) {
  console.log('Seeding issues...');

  const issues = [
    // Urgent Issues (21-40)
    {
      issueType: 'Urgent',
      description: 'Water shortage during summer disrupts ritual and hospitality',
      preventiveAction: 'Store emergency water; reuse wisely; assign water steward',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder'
    },
    {
      issueType: 'Urgent',
      description: 'Power cut during evening lamp lighting or chanting',
      preventiveAction: 'Keep oil lamps and battery backups ready',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Guest arrives unannounced with no food or space prepared',
      preventiveAction: 'Maintain guest shelf with dry snacks and water; assign greeting role',
      role: 'Grand Mother',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Urgent',
      description: 'Missed shraddha due to calendar confusion',
      preventiveAction: 'Sync family calendar; assign reminder role; prepare backup ritual',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Child forgets school project due on festival day',
      preventiveAction: 'Create festival-week duty lightening plan; assign youth mentor',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'Delivery worker arrives during sacred ritual',
      preventiveAction: 'Assign buffer role to receive guests; post sacred time signage',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Temple priest unavailable for scheduled ritual',
      preventiveAction: 'Train backup ritual performer; maintain home altar protocol',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Sudden rain disrupts outdoor ancestral ceremony',
      preventiveAction: 'Prepare indoor backup space; keep waterproof coverings',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Child refuses to participate in family ritual',
      preventiveAction: 'Create child-friendly ritual version; assign storytelling role',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'No one available to light lamp due to travel or work',
      preventiveAction: 'Assign rotating lamp duty; use reminder assistant',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Festival food delayed due to market closure',
      preventiveAction: 'Stock dry ingredients; assign emergency cook role',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Youth overwhelmed by exams skips sacred duties',
      preventiveAction: 'Offer lightened duty path; create exam-week rituals',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'Elder forgets verse during chanting',
      preventiveAction: 'Keep laminated verse cards; assign chant buddy',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Family forgets to invite neighbor for shared ritual',
      preventiveAction: 'Create invite checklist; assign hospitality role',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Child spills oil near altar during puja',
      preventiveAction: 'Keep cleanup kit nearby; assign altar safety monitor',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'Youth posts insensitive comment during sacred time',
      preventiveAction: 'Create social media boundaries; assign digital dharma guide',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'Sacred plant wilts due to heat wave',
      preventiveAction: 'Assign plant guardian; install shade or water system',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Urgent',
      description: 'Family forgets to perform monthly ancestor ritual',
      preventiveAction: 'Create monthly ritual calendar; assign memory keeper',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Festival prep overlaps with school exam schedule',
      preventiveAction: 'Create shared calendar; assign youth-friendly festival roles',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'No one available to clean sacred space before ritual',
      preventiveAction: 'Assign rotating cleaning duty; create pre-ritual checklist',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    // Repair Issues (41-60)
    {
      issueType: 'Repair',
      description: 'Broken lamp stand prevents safe lighting of sacred flame',
      preventiveAction: 'Monthly altar inspection; replace damaged items',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Torn pages in Tirukkural or Naladiyar make verses unreadable',
      preventiveAction: 'Laminate key verses; digitize backups',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Repair',
      description: 'Sibling conflict during festival prep causes emotional strain',
      preventiveAction: 'Schedule forgiveness rituals; assign neutral mediator',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Repair',
      description: 'Lost tools for planting or cleaning disrupt ecology duties',
      preventiveAction: 'Label and store tools per virtue zone',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Prayer space cluttered with unused items',
      preventiveAction: 'Create monthly declutter ritual; assign space steward',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Family memory journal damaged by water or insects',
      preventiveAction: 'Digitize records; store backups in cloud and print',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Repair',
      description: 'Children unaware of ancestral names or stories',
      preventiveAction: 'Monthly storytelling sessions; memory cards',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Repair',
      description: 'Altar cloth torn or stained',
      preventiveAction: 'Keep backup cloths; assign altar maintenance role',
      role: 'Mother',
      urgencyLevel: 'Low',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Festival decorations broken or missing',
      preventiveAction: 'Create reusable decoration kits; assign repair role',
      role: 'Sister',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Repair',
      description: 'Role confusion during shared rituals',
      preventiveAction: 'Use role cards; clarify duties before event',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Repair',
      description: 'Sacred plant pot cracked or leaking',
      preventiveAction: 'Replace pot; assign plant guardian',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Children disengaged from slow or unclear rituals',
      preventiveAction: 'Create visual guides; use story-based onboarding',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Repair',
      description: 'Family tree record lost or outdated',
      preventiveAction: 'Update and print family tree quarterly',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Repair',
      description: 'Sacred vessel chipped or unsafe',
      preventiveAction: 'Inspect vessels monthly; replace with reverence',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Repair',
      description: 'Digital assistant reminders not syncing',
      preventiveAction: 'Check calendar integration; assign tech steward',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Repair',
      description: 'Festival food preparation delayed due to missing utensils',
      preventiveAction: 'Maintain festival kitchen checklist',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Children mock ancestral rituals out of boredom',
      preventiveAction: 'Create pride-based onboarding; assign storytelling role',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Repair',
      description: 'Prayer bell or conch broken',
      preventiveAction: 'Keep backup instruments; assign sound steward',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Repair',
      description: 'Family altar not facing correct direction',
      preventiveAction: 'Realign altar; consult Agama guidelines',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Repair',
      description: 'Sacred grove fence damaged by animals',
      preventiveAction: 'Repair fence; assign grove guardian',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    // Maintenance Issues (61-72)
    {
      issueType: 'Maintenance',
      description: 'Dust accumulation in prayer space dulls sacred atmosphere',
      preventiveAction: 'Weekly cleaning rota; assign altar steward',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Sacred plants overgrown or neglected',
      preventiveAction: 'Seasonal pruning calendar; assign plant guardian',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Children forget ancestral names and stories',
      preventiveAction: 'Monthly storytelling sessions; memory cards',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Maintenance',
      description: 'Food waste during festivals due to poor planning',
      preventiveAction: 'Portion control; compost rituals; assign food planner',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Virtue reminders not reaching family members',
      preventiveAction: 'Use assistant alerts; print virtue-of-the-week cards',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Maintenance',
      description: 'Prayer books and chant sheets wear out',
      preventiveAction: 'Laminate key pages; keep backups',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Maintenance',
      description: 'Altar cloths and vessels not cleaned regularly',
      preventiveAction: 'Create monthly altar care checklist',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Festival prep always rushed or chaotic',
      preventiveAction: 'Create festival prep calendar; assign roles early',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Children disengaged from rituals over time',
      preventiveAction: 'Create child-friendly formats; rotate storytelling',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Maintenance',
      description: 'Family tree not updated with new births or marriages',
      preventiveAction: 'Quarterly update ritual; assign memory keeper',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Maintenance',
      description: 'Sacred grove fence weakens over time',
      preventiveAction: 'Inspect and repair seasonally; assign grove guardian',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'Digital assistant reminders misaligned with sunrise/sunset',
      preventiveAction: 'Sync with Panchang; adjust assistant logic',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Upgrade Issues (73-83)
    {
      issueType: 'Upgrade',
      description: 'Children disengaged from slow or unclear rituals',
      preventiveAction: 'Create visual guides; use story-based onboarding',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Upgrade',
      description: 'Elders struggle to access sacred spaces',
      preventiveAction: 'Install ramps, cushions, shaded areas',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Upgrade',
      description: 'Family records only stored in paper form',
      preventiveAction: 'Digitize and sync to cloud; print backups',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Upgrade',
      description: 'Role confusion during shared rituals',
      preventiveAction: 'Use role cards; clarify duties before event',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Upgrade',
      description: 'No Tamil-English toggle in assistant or planner',
      preventiveAction: 'Add bilingual chant cards and UI toggle',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Upgrade',
      description: 'Festival rituals feel repetitive or mechanical',
      preventiveAction: 'Add meaning cards; rotate themes',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Upgrade',
      description: 'Children unaware of sacred geography (rivers, groves)',
      preventiveAction: 'Create map-based storytelling sessions',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Upgrade',
      description: 'No karma tracking or reward system',
      preventiveAction: 'Add karma point dashboard; celebrate completions',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Upgrade',
      description: 'No onboarding for new family members',
      preventiveAction: 'Create welcome ritual and role introduction cards',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Upgrade',
      description: 'No visual planner for sacred timings',
      preventiveAction: 'Create sunrise/sunset-based calendar view',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Upgrade',
      description: 'No backup for sacred music or chants',
      preventiveAction: 'Record and store audio files; assign chant archivist',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    // Cultural Displacement Issues (84-93)
    {
      issueType: 'Cultural Displacement',
      description: 'Social media mocks sacred dress or rituals',
      preventiveAction: 'Teach sacred humor; create pride-based onboarding',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'English-only rituals lose Tamil depth',
      preventiveAction: 'Add Tamil-English toggles; bilingual chant cards',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Imported holidays overshadow ancestral ones',
      preventiveAction: 'Create parallel rituals; explain meaning to children',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Youth embarrassed by ancestral practices',
      preventiveAction: 'Create pride rituals; assign storytelling mentor',
      role: 'Grand Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'TV or ads promote values opposite to restraint',
      preventiveAction: 'Create media literacy sessions; assign virtue filter',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Online games promote gambling or violence',
      preventiveAction: 'Set screen boundaries; offer sacred alternatives',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Sacred touch misunderstood in modern context',
      preventiveAction: 'Teach boundaries and meaning; use role-based guides',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Children unaware of local temple traditions',
      preventiveAction: 'Create temple visit rituals; assign temple guide',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Ancestral language fading in daily speech',
      preventiveAction: 'Create language revival rituals; assign word-of-the-day',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Mockery of sacred food or fasting practices',
      preventiveAction: 'Teach meaning behind food rituals; create story cards',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    // Emotional Freeze Issues (94-101)
    {
      issueType: 'Emotional Freeze',
      description: 'Grief after elder\'s death blocks ancestral rituals',
      preventiveAction: 'Prepare grief-aware rituals; assign emotional support role',
      role: 'Grand Mother',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Sibling resentment prevents shared festival prep',
      preventiveAction: 'Schedule forgiveness rituals; assign neutral mediator',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Shame prevents youth from joining sacred chant',
      preventiveAction: 'Create pride-based chant onboarding; assign chant buddy',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Guilt over missed duties leads to withdrawal',
      preventiveAction: 'Create restart rituals; offer karma forgiveness flow',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Fear of judgment blocks confession or apology',
      preventiveAction: 'Create safe apology rituals; assign listening role',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Family avoids ancestral rituals due to past trauma',
      preventiveAction: 'Offer healing rituals; allow symbolic participation',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Child refuses to speak during family meals',
      preventiveAction: 'Create gentle conversation rituals; assign story starter',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Elder avoids sacred duties due to feeling obsolete',
      preventiveAction: 'Assign legacy roles; create elder honor rituals',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    // Ambiguity Issues (102-109)
    {
      issueType: 'Ambiguity',
      description: 'No clarity on who lights lamp each day',
      preventiveAction: 'Assign rotating lamp duty; use reminder assistant',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Ambiguity',
      description: 'Overlap between Admin and Father during festival prep',
      preventiveAction: 'Use role cards; clarify duties before event',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Ambiguity',
      description: 'Children unsure when to greet elders',
      preventiveAction: 'Create greeting rituals; assign elder welcome role',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Ambiguity',
      description: 'Multiple people assume altar cleaning is someone else\'s job',
      preventiveAction: 'Assign altar steward; use duty checklist',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Ambiguity',
      description: 'No one knows who leads ancestral ritual this year',
      preventiveAction: 'Assign memory keeper; rotate ritual lead annually',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Ambiguity',
      description: 'Youth unsure when to participate in chanting',
      preventiveAction: 'Create chant schedule; assign chant buddy',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Ambiguity',
      description: 'Family unsure who invites neighbors for shared rituals',
      preventiveAction: 'Assign hospitality role; use invite checklist',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Ambiguity',
      description: 'No clarity on who updates family tree',
      preventiveAction: 'Assign memory keeper; schedule quarterly updates',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    // Role Drift Issues (110-117)
    {
      issueType: 'Role Drift',
      description: 'Grandmother now caregiver but duties unchanged',
      preventiveAction: 'Update role map; assign caregiving duties formally',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Role Drift',
      description: 'Youth taking on admin tasks without guidance',
      preventiveAction: 'Create youth onboarding; assign mentor',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Role Drift',
      description: 'Father role split across two siblings',
      preventiveAction: 'Clarify shared duties; assign festival lead',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Role Drift',
      description: 'Mother now earning but still holds all household duties',
      preventiveAction: 'Redistribute duties; honor dual roles',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Role Drift',
      description: 'Elder unable to perform physical rituals but still expected to',
      preventiveAction: 'Assign symbolic roles; offer seated alternatives',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Role Drift',
      description: 'Youth expected to perform rituals without training',
      preventiveAction: 'Create youth ritual training flow',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Role Drift',
      description: 'Admin role unclear after elder\'s passing',
      preventiveAction: 'Reassign admin duties; create succession ritual',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Role Drift',
      description: 'Children expected to behave like adults during rituals',
      preventiveAction: 'Create child-friendly formats; assign playful roles',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    // Neglect Issues (118-127)
    {
      issueType: 'Neglect',
      description: 'Altar unused for weeks due to busy schedules',
      preventiveAction: 'Create weekly altar check-in; assign altar steward',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Neglect',
      description: 'Children forget ancestral names over time',
      preventiveAction: 'Use memory cards; monthly storytelling sessions',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Neglect',
      description: 'Sacred plants dry out from lack of watering',
      preventiveAction: 'Assign plant guardian; use watering reminders',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Neglect',
      description: 'Family forgets to chant or recite mantras',
      preventiveAction: 'Create chant-of-the-week flow; assign chant buddy',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Neglect',
      description: 'No one updates family tree after new birth',
      preventiveAction: 'Quarterly update ritual; assign memory keeper',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Neglect',
      description: 'Virtue reminders stop after initial enthusiasm',
      preventiveAction: 'Use assistant nudges; rotate virtue-of-the-week',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Neglect',
      description: 'Sacred books gather dust and go unread',
      preventiveAction: 'Assign verse reader; create reading circle',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Neglect',
      description: 'Children unaware of meaning behind rituals',
      preventiveAction: 'Create story-based onboarding; assign ritual explainer',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Neglect',
      description: 'Festival prep always last-minute and stressful',
      preventiveAction: 'Create festival prep calendar; assign lead roles',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Neglect',
      description: 'No one maintains sacred fire tools',
      preventiveAction: 'Create seasonal fire tool inspection checklist',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    // Cognitive Overload Issues (128-135)
    {
      issueType: 'Cognitive Overload',
      description: 'Too many duties assigned during festival week',
      preventiveAction: 'Use karma-weighted prioritization; simplify flows',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Youth overwhelmed by school and sacred duties',
      preventiveAction: 'Create exam-week duty lightening plan',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Elder forgets multiple rituals in one day',
      preventiveAction: 'Use visual planner; assign ritual buddy',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Multiple reminders cause stress instead of support',
      preventiveAction: 'Stagger reminders; use calming tones',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Mother handles cooking, hosting, and rituals alone',
      preventiveAction: 'Redistribute duties; assign festival co-leads',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Children confused by overlapping instructions',
      preventiveAction: 'Use visual duty cards; assign single point of contact',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Admin overwhelmed by tracking all family rituals',
      preventiveAction: 'Create shared dashboard; assign co-admin',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Cognitive Overload',
      description: 'Too many virtue reminders in one morning',
      preventiveAction: 'Limit to one virtue per day; rotate weekly',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Event Issues (136-145)
    {
      issueType: 'Event',
      description: 'Marriage introduces new family member with unclear role',
      preventiveAction: 'Create welcome ritual; assign onboarding guide',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Event',
      description: 'Birth of child shifts household rhythms',
      preventiveAction: 'Reassign duties; create newborn care rituals',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Event',
      description: 'Relocation disrupts sacred space and routines',
      preventiveAction: 'Create portable altar kits; travel duty packs',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Event',
      description: 'Exam season alters youth participation in rituals',
      preventiveAction: 'Create exam-week rituals; lighten duties',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Event',
      description: 'Death in extended family pauses all duties',
      preventiveAction: 'Prepare condolence rituals; pause respectfully',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Event',
      description: 'Festival overlaps with school or work deadlines',
      preventiveAction: 'Create shared calendar; assign flexible roles',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Event',
      description: 'Pilgrimage or temple trip changes daily flow',
      preventiveAction: 'Assign travel duties; create mobile ritual plan',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Event',
      description: 'New job or retirement changes role expectations',
      preventiveAction: 'Update role map; create transition rituals',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Event',
      description: 'Family reunion brings intergenerational role confusion',
      preventiveAction: 'Use role cards; assign ritual leads by stage',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Event',
      description: 'Festival celebrated differently in spouse\'s family',
      preventiveAction: 'Create shared ritual blend; honor both traditions',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    // Additional Maintenance Issues (146-149)
    {
      issueType: 'Maintenance',
      description: 'Sacred corner used for storage or clutter',
      preventiveAction: 'Create a visible, clean \'quiet zone\' with lamp and incense',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Maintenance',
      description: 'No rhythm for meals, sleep, or family time',
      preventiveAction: 'Use shared calendar with gentle reminders',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Maintenance',
      description: 'Children unaware of local traditions or festivals',
      preventiveAction: 'Add festival cards to fridge or assistant dashboard',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Maintenance',
      description: 'No shared space for reflection or silence',
      preventiveAction: 'Designate a \'pause corner\' with cushions or incense',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Additional Urgent Issues (150-154)
    {
      issueType: 'Urgent',
      description: 'School or work deadlines clash with family events',
      preventiveAction: 'Create shared planner with conflict alerts',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Urgent',
      description: 'No food or seating ready for surprise guests',
      preventiveAction: 'Maintain guest shelf with dry snacks and folding chairs',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Urgent',
      description: 'Elder needs help but no one is available',
      preventiveAction: 'Assign emergency contact and backup caregiver',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Urgent',
      description: 'Child overwhelmed by school and screen time',
      preventiveAction: 'Create \'screen-free hour\' with calming activities',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Urgent',
      description: 'Festival prep delayed due to traffic or delivery issues',
      preventiveAction: 'Stock essentials early; assign festival prep lead',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    // Additional Emotional Freeze Issues (155-159)
    {
      issueType: 'Emotional Freeze',
      description: 'Family avoids rituals due to past religious trauma',
      preventiveAction: 'Create new rituals focused on values, not doctrine',
      role: 'Grand Father',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Shame or awkwardness around chanting or prayer',
      preventiveAction: 'Use music or nature sounds to ease into sacred rhythm',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Guilt over not knowing traditions',
      preventiveAction: 'Start with one virtue or story per week',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Resentment over unequal household duties',
      preventiveAction: 'Use karma point system or rotating duty cards',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Emotional Freeze',
      description: 'Grief from loss blocks celebration or connection',
      preventiveAction: 'Create memory rituals with photos and stories',
      role: 'Grand Mother',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    // Additional Ambiguity Issues (160-164)
    {
      issueType: 'Ambiguity',
      description: 'No clarity on who does what in the household',
      preventiveAction: 'Create role cards or duty dashboard',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Ambiguity',
      description: 'Children unsure when to help or participate',
      preventiveAction: 'Use visual cues or assistant nudges',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Ambiguity',
      description: 'No shared understanding of what \'sacred\' means',
      preventiveAction: 'Define family values together—kindness, care, rhythm',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Ambiguity',
      description: 'Festival rituals vary across generations',
      preventiveAction: 'Blend traditions with mutual respect',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Ambiguity',
      description: 'No one knows how to start a ritual or prayer',
      preventiveAction: 'Create \'starter rituals\' with simple steps',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Additional Role Drift Issues (165-169)
    {
      issueType: 'Role Drift',
      description: 'Working parents still expected to manage all rituals',
      preventiveAction: 'Redistribute duties; honor dual roles',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Role Drift',
      description: 'Grandparents now caregivers but not included in planning',
      preventiveAction: 'Include them in decision-making and ritual design',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Role Drift',
      description: 'Children expected to behave like adults during rituals',
      preventiveAction: 'Create playful, age-appropriate formats',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Role Drift',
      description: 'Teenagers disengaged due to lack of relevance',
      preventiveAction: 'Let them lead one ritual or choose a virtue to explore',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Role Drift',
      description: 'No one updates roles after marriage or relocation',
      preventiveAction: 'Create transition rituals and role onboarding',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Additional Cultural Displacement Issues (170-174)
    {
      issueType: 'Cultural Displacement',
      description: 'Social media mocks traditional values',
      preventiveAction: 'Create pride-based onboarding and storytelling',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'English-only rituals lose emotional depth',
      preventiveAction: 'Add bilingual cards or assistant toggles',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Children unaware of local temple or nature traditions',
      preventiveAction: 'Plan monthly visits or nature walks',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Imported holidays overshadow ancestral ones',
      preventiveAction: 'Blend celebrations with local meaning',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Cultural Displacement',
      description: 'Sacred food or dress seen as outdated',
      preventiveAction: 'Share stories behind choices; celebrate with pride',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    // Transition Issues (175-181)
    {
      issueType: 'Transition',
      description: 'Teen enters puberty and withdraws from family rituals',
      preventiveAction: 'Create transition ritual; assign youth mentor',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Transition',
      description: 'Marriage shifts household roles and expectations',
      preventiveAction: 'Create welcome ritual; update role map',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Transition',
      description: 'Retirement leaves elder feeling purposeless',
      preventiveAction: 'Assign legacy duties; create elder honor rituals',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Transition',
      description: 'Widowhood disrupts ancestral rituals and memory',
      preventiveAction: 'Offer symbolic participation; create healing rituals',
      role: 'Grand Mother',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Transition',
      description: 'Child starts school and loses rhythm of home duties',
      preventiveAction: 'Create school-day ritual flow; assign morning buddy',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Transition',
      description: 'New baby shifts sleep and meal rhythms',
      preventiveAction: 'Reassign duties; create newborn care rituals',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Transition',
      description: 'Youth moves out for college or work',
      preventiveAction: 'Create departure ritual; assign memory keeper',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'Youth',
    },
    // Misalignment Issues (182-187)
    {
      issueType: 'Misalignment',
      description: 'Assistant reminders clash with real-world timing',
      preventiveAction: 'Sync with sunrise/sunset; allow manual override',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Misalignment',
      description: 'Digital planner doesn\'t reflect emotional readiness',
      preventiveAction: 'Add emotional check-in before assigning duties',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Misalignment',
      description: 'Virtue-of-the-day feels irrelevant to current mood',
      preventiveAction: 'Allow user selection or mood-based rotation',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    {
      issueType: 'Misalignment',
      description: 'Assistant assigns duties during grief or illness',
      preventiveAction: 'Pause planner; activate healing mode',
      role: 'Father',
      urgencyLevel: 'High',
      lifeStage: 'All',
    },
    {
      issueType: 'Misalignment',
      description: 'Festival prep reminders ignore school exam schedules',
      preventiveAction: 'Integrate school calendar; adjust duty load',
      role: 'Mother',
      urgencyLevel: 'High',
      lifeStage: 'Youth',
    },
    {
      issueType: 'Misalignment',
      description: 'Role cards don\'t reflect actual family dynamics',
      preventiveAction: 'Allow custom role mapping; review monthly',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    },
    // Substitution Issues (188-194)
    {
      issueType: 'Substitution',
      description: 'Electric lamp replaces oil lamp with no ritual',
      preventiveAction: 'Add intention ritual before switching on',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Substitution',
      description: 'Online chanting lacks emotional connection',
      preventiveAction: 'Use audio with meaning cards; assign chant buddy',
      role: 'Grand Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Substitution',
      description: 'Synthetic flowers used in puja lose fragrance and meaning',
      preventiveAction: 'Blend with natural offerings; explain symbolism',
      role: 'Father',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Substitution',
      description: 'Digital shraddha lacks ancestral presence',
      preventiveAction: 'Add photo ritual or memory sharing before online rites',
      role: 'Admin',
      urgencyLevel: 'High',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Substitution',
      description: 'Plastic vessels used for sacred offerings',
      preventiveAction: 'Use natural materials; assign vessel steward',
      role: 'Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Householder',
    },
    {
      issueType: 'Substitution',
      description: 'Online temple visits replace physical darshan',
      preventiveAction: 'Create home darshan ritual with altar and incense',
      role: 'Grand Mother',
      urgencyLevel: 'Medium',
      lifeStage: 'Elder',
    },
    {
      issueType: 'Substitution',
      description: 'Pre-recorded mantras replace live chanting',
      preventiveAction: 'Schedule live chant circle monthly',
      role: 'Admin',
      urgencyLevel: 'Medium',
      lifeStage: 'All',
    }
  ];

  for (const issueData of issues) {
    // Create the issue
    await prisma.issue.create({
      data: issueData
    });
  }

  console.log('Issues seeded successfully');
}