import { PrismaClient } from '@prisma/client';

export async function seedVirtues(prisma: PrismaClient) {
  console.log('Seeding virtues...');

  const virtues = [
    // Virtues 1-10
    {
      virtueName: 'தான தருமம் (பொருள்) / Generosity (Material)',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 16,
      viceAvoided: 'Greed',
      sourceText: 'Tirukkural 22',
      sourceType: 'Tamil Classical',
      description: 'Giving material possessions generously',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'தான தருமம் (ஆன்மீக) / Generosity (Spiritual)',
      virtueType: 'Spiritual',
      virtueCategory: 'Service',
      virtueStage: 'Elder',
      karmaPoints: 18,
      viceAvoided: 'Selfishness',
      sourceText: 'Tirukkural 23',
      sourceType: 'Tamil Classical',
      description: 'Sharing spiritual knowledge and wisdom',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father, Admin',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'தான தருமம் (காப்பு) / Generosity (Protective)',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'Householder',
      karmaPoints: 20,
      viceAvoided: 'Neglect',
      sourceText: 'Tirukkural 24',
      sourceType: 'Tamil Classical',
      description: 'Protecting and providing shelter to those in need',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Admin',
      recommendedFrequency: 'As needed'
    },
    {
      virtueName: 'தொண்டு / Charity',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 22,
      viceAvoided: 'Indifference',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Performing charitable acts for the benefit of others',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பிறர்நலம் / Altruism',
      virtueType: 'Moral',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 24,
      viceAvoided: 'Self-centeredness',
      sourceText: 'Tirukkural 25',
      sourceType: 'Tamil Classical',
      description: 'Acting for the welfare of others without self-interest',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'தன்னலமின்மை / Selflessness',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 26,
      viceAvoided: 'Ego',
      sourceText: 'Tirukkural 26',
      sourceType: 'Tamil Classical',
      description: 'Acting without regard for personal gain',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'கருணை / Compassion',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 28,
      viceAvoided: 'Cruelty',
      sourceText: 'Tirukkural 27',
      sourceType: 'Tamil Classical',
      description: 'Showing compassion and mercy towards all beings',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'உணர்வு பகிர்வு / Empathy',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 30,
      viceAvoided: 'Insensitivity',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Understanding and sharing the feelings of others',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'நன்மை / Kindness',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 32,
      viceAvoided: 'Harshness',
      sourceText: 'Tirukkural 28',
      sourceType: 'Tamil Classical',
      description: 'Showing kindness and gentleness in actions and words',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'நன்மை செயல் / Benevolence',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'Householder',
      karmaPoints: 34,
      viceAvoided: 'Malevolence',
      sourceText: 'Tirukkural 29',
      sourceType: 'Tamil Classical',
      description: 'Actively doing good and promoting welfare',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Admin',
      recommendedFrequency: 'Weekly'
    },
    // Virtues 11-20
    {
      virtueName: 'விருந்தோம்பல் / Hospitality',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'Householder',
      karmaPoints: 36,
      viceAvoided: 'Neglect',
      sourceText: 'Tirukkural 9',
      sourceType: 'Tamil Classical',
      description: 'Hospitality and welcoming guests',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Mother, Grand Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'இனியவைகூறல் / Pleasant Speech',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 38,
      viceAvoided: 'Harshness',
      sourceText: 'Tirukkural 10',
      sourceType: 'Tamil Classical',
      description: 'Speaking pleasantly and kindly',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'நடுவுநிலைமை / Impartiality',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'Elder',
      karmaPoints: 40,
      viceAvoided: 'Bias',
      sourceText: 'Tirukkural 12',
      sourceType: 'Tamil Classical',
      description: 'Maintaining impartiality and fairness',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Grand Father, Admin',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'கொல்லாமை / Non-killing',
      virtueType: 'Moral',
      virtueCategory: 'Universal Ethics',
      virtueStage: 'All',
      karmaPoints: 42,
      viceAvoided: 'Violence',
      sourceText: 'Tirukkural 33',
      sourceType: 'Tamil Classical',
      description: 'Avoiding harm to living beings',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'ஒழுக்கம் / Decorum',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Youth',
      karmaPoints: 44,
      viceAvoided: 'Indecency',
      sourceText: 'Tirukkural 14',
      sourceType: 'Tamil Classical',
      description: 'Maintaining proper conduct and decorum',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Brother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'மனநிறைவு / Contentment',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 46,
      viceAvoided: 'Greed',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Finding contentment and satisfaction',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பிறர்பழி கூறாமை / Avoiding Gossip',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 48,
      viceAvoided: 'Slander',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Avoiding gossip and speaking ill of others',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Admin',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'பிறர்மனை நோக்காமை / Avoiding Lustful Gaze',
      virtueType: 'Moral',
      virtueCategory: 'Family Ethics',
      virtueStage: 'Youth',
      karmaPoints: 50,
      viceAvoided: 'Lust',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Avoiding lustful thoughts and gazes',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Brother, Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'கடவுள் வாழ்த்து / Praise of God',
      virtueType: 'Spiritual',
      virtueCategory: 'Devotion',
      virtueStage: 'All',
      karmaPoints: 52,
      viceAvoided: 'Atheism',
      sourceText: 'Tirukkural 1',
      sourceType: 'Tamil Classical',
      description: 'Praising and worshiping God',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father, Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'உலக நலன் / Universal Welfare',
      virtueType: 'Spiritual',
      virtueCategory: 'Universal Ethics',
      virtueStage: 'Elder',
      karmaPoints: 54,
      viceAvoided: 'Selfishness',
      sourceText: 'Thirumoolar',
      sourceType: 'Tamil Classical',
      description: 'Working for the welfare of all beings',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father, Admin',
      recommendedFrequency: 'Monthly'
    },
    // Virtues 21-30
    {
      virtueName: 'பசுமை பராமரிப்பு / Care for Nature',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 56,
      viceAvoided: 'Neglect of nature',
      sourceText: 'Siru Panchamoolam',
      sourceType: 'Folk Tradition',
      description: 'Caring for and protecting nature',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Mother, Admin',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'தண்ணீர் வழங்கல் / Giving Water',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 58,
      viceAvoided: 'Withholding help',
      sourceText: 'Siru Panchamoolam',
      sourceType: 'Folk Tradition',
      description: 'Providing water to those in need',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Grand Mother, Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'சாலை அமைத்தல் / Building Roads with Shade',
      virtueType: 'Civic',
      virtueCategory: 'Service',
      virtueStage: 'Elder',
      karmaPoints: 60,
      viceAvoided: 'Selfishness',
      sourceText: 'Siru Panchamoolam',
      sourceType: 'Folk Tradition',
      description: 'Building shaded roads for public benefit',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Grand Father, Admin',
      recommendedFrequency: 'Seasonal'
    },
    {
      virtueName: 'பெரியோர் மரியாதை / Respect for Elders',
      virtueType: 'Social',
      virtueCategory: 'Family Ethics',
      virtueStage: 'Youth',
      karmaPoints: 62,
      viceAvoided: 'Disrespect',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Showing respect to elders',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Brother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'குடும்ப ஒற்றுமை / Family Unity',
      virtueType: 'Social',
      virtueCategory: 'Family Ethics',
      virtueStage: 'All',
      karmaPoints: 64,
      viceAvoided: 'Division',
      sourceText: 'Eladi',
      sourceType: 'Tamil Classical',
      description: 'Maintaining family unity and harmony',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Mother',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'ஆன்ம நலம் / Soul Purity',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 66,
      viceAvoided: 'Ego, Impurity',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Maintaining purity of the soul',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'பிறர்க்கு தீமை பேசாமை / Avoiding Slander',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 68,
      viceAvoided: 'Slander',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Avoiding slander and harmful speech',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Admin',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'தவம் / Austerity',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 70,
      viceAvoided: 'Indulgence',
      sourceText: 'Tirukkural 27',
      sourceType: 'Tamil Classical',
      description: 'Practicing austerity and self-discipline',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'மக்கட்பேறு / Wealth of Children',
      virtueType: 'Domestic',
      virtueCategory: 'Family Ethics',
      virtueStage: 'Householder',
      karmaPoints: 72,
      viceAvoided: 'Neglect of heirs',
      sourceText: 'Tirukkural 7',
      sourceType: 'Tamil Classical',
      description: 'Raising virtuous children',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Mother',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'வாழ்க்கைத் துணைநலம் / Worth of a Wife',
      virtueType: 'Domestic',
      virtueCategory: 'Family Ethics',
      virtueStage: 'Householder',
      karmaPoints: 74,
      viceAvoided: 'Disrespect of spouse',
      sourceText: 'Tirukkural 6',
      sourceType: 'Tamil Classical',
      description: 'Valuing and respecting one\'s spouse',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Mother',
      recommendedFrequency: 'Monthly'
    },
    // Virtues 31-40
    {
      virtueName: 'நீத்தார் பெருமை / Greatness of Ascetics',
      virtueType: 'Spiritual',
      virtueCategory: 'Universal Ethics',
      virtueStage: 'Elder',
      karmaPoints: 76,
      viceAvoided: 'Ego, Attachment',
      sourceText: 'Tirukkural 3',
      sourceType: 'Tamil Classical',
      description: 'Recognizing the greatness of renunciants',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'வான்சிறப்பு / Blessing of Rain',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 78,
      viceAvoided: 'Environmental neglect',
      sourceText: 'Tirukkural 2',
      sourceType: 'Tamil Classical',
      description: 'Appreciating the blessing of rain',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Admin, Grand Father',
      recommendedFrequency: 'Seasonal'
    },
    {
      virtueName: 'இல்வாழ்க்கை / Domestic Virtue',
      virtueType: 'Domestic',
      virtueCategory: 'Family Ethics',
      virtueStage: 'Householder',
      karmaPoints: 80,
      viceAvoided: 'Family neglect',
      sourceText: 'Tirukkural 5',
      sourceType: 'Tamil Classical',
      description: 'Maintaining virtue in domestic life',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'மெய்யுணர்தல் / Truth-Consciousness',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 82,
      viceAvoided: 'Delusion',
      sourceText: 'Tirukkural 36',
      sourceType: 'Tamil Classical',
      description: 'Consciousness of truth and reality',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பிறர்க்கு உதவி / Helping Others',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 84,
      viceAvoided: 'Indifference',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Helping others in need',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பிறர்க்கு பொறுப்பு / Responsibility to Others',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 86,
      viceAvoided: 'Neglect',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Taking responsibility for others\' welfare',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Admin, Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'சத்தியம் / Oath-Keeping',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Householder',
      karmaPoints: 88,
      viceAvoided: 'Betrayal',
      sourceText: 'Tirukkural 298',
      sourceType: 'Tamil Classical',
      description: 'Keeping promises and oaths',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Admin',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'பாவமில்லாமை / Sinlessness',
      virtueType: 'Spiritual',
      virtueCategory: 'Universal Ethics',
      virtueStage: 'Elder',
      karmaPoints: 90,
      viceAvoided: 'Sinful action',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Living without committing sins',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'பசுவின்பால் கருணை / Kindness to Animals',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 92,
      viceAvoided: 'Cruelty',
      sourceText: 'Folk Tradition',
      sourceType: 'Folk Tradition',
      description: 'Showing kindness to animals',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Brother, Mother',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பசுவின் பாதுகாப்பு / Protection of Cows',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 94,
      viceAvoided: 'Violence',
      sourceText: 'Folk Tradition',
      sourceType: 'Folk Tradition',
      description: 'Protecting and caring for cows',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Father, Grand Father',
      recommendedFrequency: 'Monthly'
    },
    // Virtues 41-55
    {
      virtueName: 'அன்பு / Lovingkindness',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 96,
      viceAvoided: 'Hatred',
      sourceText: 'Tirukkural 8',
      sourceType: 'Tamil Classical',
      description: 'Cultivating love and kindness',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'சிரத்தை / Reverence',
      virtueType: 'Spiritual',
      virtueCategory: 'Devotion',
      virtueStage: 'All',
      karmaPoints: 98,
      viceAvoided: 'Disrespect',
      sourceText: 'Thirumandiram',
      sourceType: 'Tamil Classical',
      description: 'Showing reverence and respect',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Grand Mother, Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'நாணம் / Modesty',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Youth',
      karmaPoints: 100,
      viceAvoided: 'Arrogance',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Practicing modesty and humility',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Brother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'நெஞ்சின் தூய்மை / Purity of Heart',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 102,
      viceAvoided: 'Hypocrisy',
      sourceText: 'Tirukkural 36',
      sourceType: 'Tamil Classical',
      description: 'Maintaining purity of heart and intention',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'சிந்தனை / Thoughtfulness',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 104,
      viceAvoided: 'Carelessness',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Being thoughtful and considerate',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Admin, Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'நேர்மை / Integrity',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 106,
      viceAvoided: 'Deceit',
      sourceText: 'Naanmanikkadigai',
      sourceType: 'Tamil Classical',
      description: 'Maintaining honesty and integrity',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Admin, Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'ஒப்புரவு / Cooperation',
      virtueType: 'Social',
      virtueCategory: 'Family Ethics',
      virtueStage: 'All',
      karmaPoints: 108,
      viceAvoided: 'Division',
      sourceText: 'Eladi',
      sourceType: 'Tamil Classical',
      description: 'Working together cooperatively',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Family',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'சுமுகம் / Cheerfulness',
      virtueType: 'Moral',
      virtueCategory: 'Social Conduct',
      virtueStage: 'All',
      karmaPoints: 110,
      viceAvoided: 'Bitterness',
      sourceText: 'Tirukkural 10',
      sourceType: 'Tamil Classical',
      description: 'Maintaining cheerfulness and positivity',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Sister, Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'சிந்தனையின் தெளிவு / Clarity of Thought',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 112,
      viceAvoided: 'Confusion',
      sourceText: 'Thirumandiram',
      sourceType: 'Tamil Classical',
      description: 'Maintaining clarity of thought and mind',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'பசித்தவர்க்கு உணவு / Feeding the Hungry',
      virtueType: 'Social',
      virtueCategory: 'Service',
      virtueStage: 'All',
      karmaPoints: 16,
      viceAvoided: 'Neglect',
      sourceText: 'Avvaiyar',
      sourceType: 'Folk Tradition',
      description: 'Feeding those who are hungry',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Mother, Grand Mother',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'தன்னம்பிக்கை / Self-Confidence',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Youth',
      karmaPoints: 18,
      viceAvoided: 'Self-doubt',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Building self-confidence and trust',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Brother, Sister',
      recommendedFrequency: 'Weekly'
    },
    {
      virtueName: 'சிந்திக்காமை தவிர்தல் / Avoiding Thoughtlessness',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 20,
      viceAvoided: 'Rashness',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Avoiding thoughtless actions',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Admin, Father',
      recommendedFrequency: 'Daily'
    },
    {
      virtueName: 'பிழை ஒப்புதல் / Admitting Mistakes',
      virtueType: 'Moral',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'All',
      karmaPoints: 22,
      viceAvoided: 'Denial',
      sourceText: 'Naladiyar',
      sourceType: 'Tamil Classical',
      description: 'Admitting mistakes and learning from them',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'All',
      recommendedFrequency: 'As needed'
    },
    {
      virtueName: 'பாவ உணர்வு / Remorse for Wrongdoing',
      virtueType: 'Spiritual',
      virtueCategory: 'Inner Discipline',
      virtueStage: 'Elder',
      karmaPoints: 24,
      viceAvoided: 'Pride',
      sourceText: 'Thirumandiram',
      sourceType: 'Tamil Classical',
      description: 'Feeling remorse for wrong actions',
      isRenunciative: true,
      isDebtClearing: true,
      isSociallyVisible: false,
      recommendedRoles: 'Grand Father',
      recommendedFrequency: 'Monthly'
    },
    {
      virtueName: 'பசுவின் பசுமை / Ecological Compassion',
      virtueType: 'Environmental',
      virtueCategory: 'Nature Ethics',
      virtueStage: 'All',
      karmaPoints: 26,
      viceAvoided: 'Exploitation',
      sourceText: 'Folk Tradition',
      sourceType: 'Folk Tradition',
      description: 'Showing compassion for ecological systems',
      isRenunciative: false,
      isDebtClearing: true,
      isSociallyVisible: true,
      recommendedRoles: 'Mother, Admin',
      recommendedFrequency: 'Weekly'
    }
  ];

  for (const virtue of virtues) {
    await prisma.virtue.create({
      data: virtue
    });
  }

  console.log('Virtues seeded successfully');
}
