import { PrismaClient } from '@prisma/client';

export async function seedArtForms(prisma: PrismaClient) {
  console.log('Seeding art forms...');

  // First, ensure we have a learning duty for art forms
  let learningDuty = await prisma.learningDuty.findFirst({
    where: { category: 'Art Forms' }
  });

  if (!learningDuty) {
    learningDuty = await prisma.learningDuty.create({
      data: {
        title: 'Art Forms and Cultural Practices',
        description: '64 traditional art forms and cultural practices from Tamil Vedic tradition',
        category: 'Art Forms',
        vedicSource: 'Tamil Classical Literature and Folk Traditions'
      }
    });
  }

  // Role tags mapping for each art form
  const roleTagsMap: { [key: number]: string } = {
    1: '["F6","F4","F10"]',
    2: '["F8","F3","F5"]',
    3: '["F5","F6","F4","F3"]',
    4: '["F4","F6","F7"]',
    5: '["F4","F3","F8"]',
    6: '["F8","F3"]',
    7: '["F6","F4","F7"]',
    8: '["F10","F1","F2"]',
    9: '["F1","F2","F8"]',
    10: '["F1","F2"]',
    11: '["F4","F1","F2"]',
    12: '["F4","F6","F7"]',
    13: '["F4","F6","F3"]',
    14: '["F6","F4"]',
    15: '["F3","F8"]',
    16: '["F4","F3"]',
    17: '["F4","F6","F7"]',
    18: '["F4","F6","F7"]',
    19: '["F1","F2","F3"]',
    20: '["F4","F3","F1","F2"]',
    21: '["F4","F6"]',
    22: '["F4","F2","F6"]',
    23: '["F3","F4","F5","F6"]',
    24: '["F6","F4","F10"]',
    25: '["F6","F4"]',
    26: '["F3","F5"]',
    27: '["F6","F4","F5"]',
    28: '["F4","F6"]',
    29: '["F6","F4","F2"]',
    30: '["F3","F5","F9"]',
    31: '["F6","F4","F10"]',
    32: '["F6","F4"]',
    33: '["F5","F6","F10"]',
    34: '["F6","F5","F10"]',
    35: '["F8","F3","F10"]',
    36: '["F4","F6","F8"]',
    37: '["F1","F2","F8"]',
    38: '["F3","F4","F9"]',
    39: '["F3","F4","F1","F2"]',
    40: '["F3","F4","F1","F2"]',
    41: '["F3","F4","F1"]',
    42: '["F3","F4","F5","F6"]',
    43: '["F4","F6","F7"]',
    44: '["F5","F6","F7"]',
    45: '["F1","F2","F4"]',
    46: '["F6","F4","F7"]',
    47: '["F5","F6","F7"]',
    48: '["F4","F2","F6"]',
    49: '["F3","F4","F1","F2"]',
    50: '["F3","F4","F1","F2"]',
    51: '["F4","F6"]',
    52: '["F3","F5"]',
    53: '["F3","F4","F8"]',
    54: '["F6","F4","F10"]',
    55: '["F3","F8"]',
    56: '["F6","F4","F10"]',
    57: '["F7","F6","F4"]',
    58: '["F4","F8","F6"]',
    59: '["F1","F2","F4"]',
    60: '["F10","F1","F2"]',
    61: '["F3","F4","F8"]',
    62: '["F3","F5"]',
    63: '["F4","F6","F10"]',
    64: '["F6","F4","F10"]'
  };

  const artForms = [
    {
      artId: 1,
      artTitle: 'Geet Vidya',
      tamilName: 'பாடல் கலை',
      virtueIds: '[46,45,43,54,13,28,12]',
      virtueWeights: '[82,79,58,92,75,25,55]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 1038,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Sacred music and chanting practices',
      roleTags: '["F6","F4","F10"]'
    },
    {
      artId: 2,
      artTitle: 'Mantra Vidya',
      tamilName: 'மந்திரம் கலை',
      virtueIds: '[46,45,54,14,13]',
      virtueWeights: '[82,79,92,89,75]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 1012,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Sacred mantra recitation and practices'
    },
    {
      artId: 3,
      artTitle: 'Stotra Pathana',
      tamilName: 'ஸ்தோத்திரம் பாடல்',
      virtueIds: '[46,43,45,54,12]',
      virtueWeights: '[82,58,79,92,55]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 984,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Recitation of devotional hymns and prayers'
    },
    {
      artId: 4,
      artTitle: 'Prarthana',
      tamilName: 'பிரார்த்தனை',
      virtueIds: '[46,45,54,12]',
      virtueWeights: '[82,79,92,55]',
      frequency: 'Daily',
      frequencyBonus: 0,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 961,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Daily prayer and supplication practices'
    },
    {
      artId: 5,
      artTitle: 'Upachara Vidhi',
      tamilName: 'அர்ச்சனை சேவை',
      virtueIds: '[22,25,33,44]',
      virtueWeights: '[91,82,32,71]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 832,
      dutyType: 'Ritual',
      lifeStage: 'Householder',
      description: 'Ritual worship and offering services'
    },
    {
      artId: 6,
      artTitle: 'Tantra Vidya',
      tamilName: 'தந்திரம் கலை',
      virtueIds: '[44,39,46,45]',
      virtueWeights: '[71,76,82,79]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 812,
      dutyType: 'Ritual',
      lifeStage: 'Elder',
      description: 'Tantric practices and esoteric knowledge'
    },
    {
      artId: 7,
      artTitle: 'Chitra Puja',
      tamilName: 'சித்திர பூஜை',
      virtueIds: '[46,48,28,39]',
      virtueWeights: '[82,76,25,76]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 798,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Icon worship and devotional painting'
    },
    {
      artId: 8,
      artTitle: 'Upadesha',
      tamilName: 'உபதேசம்',
      virtueIds: '[43,44,24,13]',
      virtueWeights: '[58,71,68,75]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 794,
      dutyType: 'Emotional',
      lifeStage: 'Elder',
      description: 'Spiritual teaching and guidance'
    },
    {
      artId: 9,
      artTitle: 'Anugraha',
      tamilName: 'ஆசி வழங்கல்',
      virtueIds: '[46,24,28,12]',
      virtueWeights: '[82,68,25,55]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 782,
      dutyType: 'Emotional',
      lifeStage: 'Elder',
      description: 'Blessing and grace-giving practices'
    },
    {
      artId: 10,
      artTitle: 'Divine Tapas',
      tamilName: 'மௌன தவம்',
      virtueIds: '[29,14,45,46]',
      virtueWeights: '[57,89,79,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 775,
      dutyType: 'Ritual',
      lifeStage: 'Elder',
      description: 'Silent meditation and austerity practices'
    },
    {
      artId: 11,
      artTitle: 'Samarpana',
      tamilName: 'சமர்ப்பணம்',
      virtueIds: '[44,46,36]',
      virtueWeights: '[71,82,16]',
      frequency: 'Festival',
      frequencyBonus: 20,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 374,
      dutyType: 'Festival',
      lifeStage: 'All',
      description: 'Complete surrender and dedication'
    },
    {
      artId: 12,
      artTitle: 'Snana Vidhi',
      tamilName: 'ஸ்நான விதி',
      virtueIds: '[39,48,31]',
      virtueWeights: '[76,76,41]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 260,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Ritual bathing and purification practices'
    },
    {
      artId: 13,
      artTitle: 'Lamp Lighting',
      tamilName: 'நெருப்பு விளக்கு',
      virtueIds: '[49,39,45]',
      virtueWeights: '[94,76,79]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 491,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Lighting sacred lamps and maintaining fire'
    },
    {
      artId: 14,
      artTitle: 'Altar Care',
      tamilName: 'பீடம் பராமரிப்பு',
      virtueIds: '[48,39,45]',
      virtueWeights: '[76,76,79]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 470,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Maintaining and decorating sacred altars'
    },
    {
      artId: 15,
      artTitle: 'Sacred Fire',
      tamilName: 'அக்னி பராமரிப்பு',
      virtueIds: '[49,39,45]',
      virtueWeights: '[94,76,79]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 491,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Maintaining sacred fire and hearth'
    },
    {
      artId: 16,
      artTitle: 'Hospitality',
      tamilName: 'விருந்தோம்பல்',
      virtueIds: '[22,5,2]',
      virtueWeights: '[91,108,112]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 499,
      dutyType: 'Emotional',
      lifeStage: 'Householder',
      description: 'Welcoming and hosting guests'
    },
    {
      artId: 17,
      artTitle: 'Food Sharing',
      tamilName: 'உணவு பகிர்வு',
      virtueIds: '[23,22,36]',
      virtueWeights: '[42,91,16]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 244,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Sharing food and meals with others'
    },
    {
      artId: 18,
      artTitle: 'Temple Visit',
      tamilName: 'கோவில் தரிசனம்',
      virtueIds: '[20,45,39]',
      virtueWeights: '[61,79,76]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 284,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Visiting temples and sacred places'
    },
    {
      artId: 19,
      artTitle: 'Ancestor Remembrance',
      tamilName: 'பிறந்தோர் நினைவு',
      virtueIds: '[21,24,55]',
      virtueWeights: '[81,68,49]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 332,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Remembering and honoring ancestors'
    },
    {
      artId: 20,
      artTitle: 'Family Unity',
      tamilName: 'குடும்ப ஒற்றுமை',
      virtueIds: '[25,24,22]',
      virtueWeights: '[82,68,91]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 388,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Maintaining family harmony and unity'
    },
    {
      artId: 21,
      artTitle: 'Needlework',
      tamilName: 'ஊசி வேலை',
      virtueIds: '[44,22,35]',
      virtueWeights: '[71,91,27]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 260,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Sewing and needlework crafts'
    },
    {
      artId: 22,
      artTitle: 'Cooking',
      tamilName: 'சமையல் கலை',
      virtueIds: '[33,22,44]',
      virtueWeights: '[32,91,71]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 260,
      dutyType: 'Daily',
      lifeStage: 'Householder',
      description: 'Art of cooking and food preparation'
    },
    {
      artId: 23,
      artTitle: 'Gardening',
      tamilName: 'தோட்ட பராமரிப்பு',
      virtueIds: '[50,44,48]',
      virtueWeights: '[34,71,76]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 260,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Gardening and plant cultivation'
    },
    {
      artId: 24,
      artTitle: 'Drama',
      tamilName: 'நாடகக் கலை',
      virtueIds: '[46,25,43]',
      virtueWeights: '[82,82,58]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 366,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Theatrical performances and drama'
    },
    {
      artId: 25,
      artTitle: 'Dance',
      tamilName: 'நடனக் கலை',
      virtueIds: '[28,22,25]',
      virtueWeights: '[25,91,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 332,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Classical and folk dance forms'
    },
    {
      artId: 26,
      artTitle: 'Sculpture',
      tamilName: 'சிற்பக் கலை',
      virtueIds: '[44,48,50]',
      virtueWeights: '[71,76,34]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 312,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Sculpting and three-dimensional art'
    },
    {
      artId: 27,
      artTitle: 'Painting',
      tamilName: 'ஓவியக் கலை',
      virtueIds: '[48,39,28]',
      virtueWeights: '[76,76,25]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 296,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Painting and visual arts'
    },
    {
      artId: 28,
      artTitle: 'Jewelry Design',
      tamilName: 'நகை வடிவமைப்பு',
      virtueIds: '[28,25,39]',
      virtueWeights: '[25,82,76]',
      frequency: 'Festival',
      frequencyBonus: 20,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 316,
      dutyType: 'Festival',
      lifeStage: 'All',
      description: 'Designing and crafting jewelry'
    },
    {
      artId: 29,
      artTitle: 'Rangoli/Kolam',
      tamilName: 'கோலம் ஓவியம்',
      virtueIds: '[48,28,46]',
      virtueWeights: '[76,25,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 304,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Floor art and decorative patterns'
    },
    {
      artId: 30,
      artTitle: 'Architecture',
      tamilName: 'கட்டிடக் கலை',
      virtueIds: '[44,48,50]',
      virtueWeights: '[71,76,34]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 312,
      dutyType: 'Logistical',
      lifeStage: 'Elder',
      description: 'Architectural design and construction'
    },
    {
      artId: 31,
      artTitle: 'Drama',
      tamilName: 'நாடகக் கலை',
      virtueIds: '[46,25,43]',
      virtueWeights: '[82,82,58]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 366,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Theatrical performances and drama'
    },
    {
      artId: 32,
      artTitle: 'Dance',
      tamilName: 'நடனக் கலை',
      virtueIds: '[28,22,25]',
      virtueWeights: '[25,91,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 332,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Classical and folk dance forms'
    },
    {
      artId: 33,
      artTitle: 'Instrumental Music',
      tamilName: 'வாத்திய கலை',
      virtueIds: '[28,25,44]',
      virtueWeights: '[25,82,71]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 429,
      dutyType: 'Emotional',
      lifeStage: 'Youth',
      description: 'Playing musical instruments'
    },
    {
      artId: 34,
      artTitle: 'Poetry Puzzle',
      tamilName: 'கவிதை புதிர்',
      virtueIds: '[43,46,44]',
      virtueWeights: '[58,82,71]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 473,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Poetic riddles and wordplay'
    },
    {
      artId: 35,
      artTitle: 'Scripture Debate',
      tamilName: 'சாஸ்திர விவாதம்',
      virtueIds: '[43,44,46]',
      virtueWeights: '[58,71,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 473,
      dutyType: 'Emotional',
      lifeStage: 'Elder',
      description: 'Debating sacred scriptures'
    },
    {
      artId: 36,
      artTitle: 'Prayer Offering',
      tamilName: 'பிரார்த்தனை அர்ப்பணம்',
      virtueIds: '[46,45,54]',
      virtueWeights: '[82,79,92]',
      frequency: 'Festival',
      frequencyBonus: 20,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 561,
      dutyType: 'Festival',
      lifeStage: 'All',
      description: 'Offering prayers during festivals'
    },
    {
      artId: 37,
      artTitle: 'Blessing Ritual',
      tamilName: 'ஆசி சடங்கு',
      virtueIds: '[46,24,28]',
      virtueWeights: '[82,68,25]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 782,
      dutyType: 'Ritual',
      lifeStage: 'Elder',
      description: 'Performing blessing ceremonies'
    },
    {
      artId: 38,
      artTitle: 'Time Management',
      tamilName: 'நேர நிர்வாகம்',
      virtueIds: '[45,44,50]',
      virtueWeights: '[79,71,34]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 253,
      dutyType: 'Logistical',
      lifeStage: 'Householder',
      description: 'Managing time and schedules effectively'
    },
    {
      artId: 39,
      artTitle: 'Seasonal Awareness',
      tamilName: 'கால பரிசீலனை',
      virtueIds: '[40,45,50]',
      virtueWeights: '[59,79,34]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 243,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Understanding seasonal cycles and changes'
    },
    {
      artId: 40,
      artTitle: 'Role Awareness',
      tamilName: 'பங்கு பரிசீலனை',
      virtueIds: '[42,44,45]',
      virtueWeights: '[45,71,79]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 253,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Understanding and fulfilling social roles'
    },
    {
      artId: 41,
      artTitle: 'Debt Clearance',
      tamilName: 'கடன் தீர்வு',
      virtueIds: '[51,44,45]',
      virtueWeights: '[68,71,79]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 253,
      dutyType: 'Logistical',
      lifeStage: 'Householder',
      description: 'Clearing debts and financial obligations'
    },
    {
      artId: 42,
      artTitle: 'Ecology Care',
      tamilName: 'சுற்றுச்சூழல் பராமரிப்பு',
      virtueIds: '[50,44,48]',
      virtueWeights: '[34,71,76]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Kriya',
      domain: 'Body',
      multiplier: 1.30,
      karmaPoints: 260,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Caring for the environment and ecology'
    },
    {
      artId: 43,
      artTitle: 'Listening',
      tamilName: 'கேட்கும் கலை',
      virtueIds: '[32,43,44]',
      virtueWeights: '[62,58,71]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 312,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'The art of attentive listening'
    },
    {
      artId: 44,
      artTitle: 'Apology',
      tamilName: 'மன்னிப்பு கோரல்',
      virtueIds: '[31,30,52]',
      virtueWeights: '[41,80,84]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 332,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Seeking forgiveness and making amends'
    },
    {
      artId: 45,
      artTitle: 'Forgiveness Ritual',
      tamilName: 'மன்னிப்பு சடங்கு',
      virtueIds: '[52,53,54]',
      virtueWeights: '[84,78,92]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 561,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Rituals of forgiveness and reconciliation'
    },
    {
      artId: 46,
      artTitle: 'Emotional Expression',
      tamilName: 'உணர்வு வெளிப்பாடு',
      virtueIds: '[27,28,5]',
      virtueWeights: '[42,25,108]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 288,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Expressing emotions appropriately'
    },
    {
      artId: 47,
      artTitle: 'Emotional Restraint',
      tamilName: 'உணர்வு கட்டுப்பாடு',
      virtueIds: '[26,7,35]',
      virtueWeights: '[35,66,27]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 208,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Controlling and managing emotions'
    },
    {
      artId: 48,
      artTitle: 'Generosity (Material)',
      tamilName: 'பொருள் தானம்',
      virtueIds: '[36,22,25]',
      virtueWeights: '[16,91,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 316,
      dutyType: 'Emotional',
      lifeStage: 'Householder',
      description: 'Giving material possessions generously'
    },
    {
      artId: 49,
      artTitle: 'Generosity (Time)',
      tamilName: 'நேர தானம்',
      virtueIds: '[37,22,25]',
      virtueWeights: '[61,91,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 366,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Giving time and service generously'
    },
    {
      artId: 50,
      artTitle: 'Generosity (Presence)',
      tamilName: 'உடன் இருப்பு தானம்',
      virtueIds: '[38,22,25]',
      virtueWeights: '[39,91,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 336,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Being present and available for others'
    },
    {
      artId: 51,
      artTitle: 'Sacred Sleep Arrangement',
      tamilName: 'படுக்கை அலங்காரம்',
      virtueIds: '[48,39,25]',
      virtueWeights: '[76,76,82]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 316,
      dutyType: 'Ritual',
      lifeStage: 'Householder',
      description: 'Arranging sacred sleeping spaces'
    },
    {
      artId: 52,
      artTitle: 'Prayer Vessel Design',
      tamilName: 'பாத்திர வடிவமைப்பு',
      virtueIds: '[48,44,50]',
      virtueWeights: '[76,71,34]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 312,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Designing vessels for prayer and rituals'
    },
    {
      artId: 53,
      artTitle: 'Auspicious Signs',
      tamilName: 'சுப சின்னம்',
      virtueIds: '[45,46,44]',
      virtueWeights: '[79,82,71]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 456,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Creating and recognizing auspicious symbols'
    },
    {
      artId: 54,
      artTitle: 'Scripture Illustration',
      tamilName: 'சித்திரக் கதைகள்',
      virtueIds: '[46,43,28]',
      virtueWeights: '[82,58,25]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 268,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Illustrating sacred stories and scriptures'
    },
    {
      artId: 55,
      artTitle: 'Symbolic Architecture',
      tamilName: 'சுப வாஸ்து தேர்வு',
      virtueIds: '[45,44,48]',
      virtueWeights: '[79,71,76]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 456,
      dutyType: 'Logistical',
      lifeStage: 'Elder',
      description: 'Designing spaces with symbolic meaning'
    },
    {
      artId: 56,
      artTitle: 'Philosophical Dance',
      tamilName: 'சாஸ்திர நடனம்',
      virtueIds: '[28,43,44]',
      virtueWeights: '[25,58,71]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 268,
      dutyType: 'Emotional',
      lifeStage: 'Elder',
      description: 'Dance expressing philosophical concepts'
    },
    {
      artId: 57,
      artTitle: 'Blessing Gesture',
      tamilName: 'வணக்கம்',
      virtueIds: '[24,31,35]',
      virtueWeights: '[68,41,27]',
      frequency: 'Daily',
      frequencyBonus: 0,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 216,
      dutyType: 'Daily',
      lifeStage: 'All',
      description: 'Gestures of blessing and respect'
    },
    {
      artId: 58,
      artTitle: 'Offering Ritual',
      tamilName: 'சமர்ப்பணம்',
      virtueIds: '[44,46,36]',
      virtueWeights: '[71,82,16]',
      frequency: 'Festival',
      frequencyBonus: 20,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 374,
      dutyType: 'Festival',
      lifeStage: 'All',
      description: 'Rituals of offering and dedication'
    },
    {
      artId: 59,
      artTitle: 'Memory Ritual',
      tamilName: 'நினைவகம்',
      virtueIds: '[46,44,31]',
      virtueWeights: '[82,71,41]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 440,
      dutyType: 'Ritual',
      lifeStage: 'Elder',
      description: 'Rituals for memory and remembrance'
    },
    {
      artId: 60,
      artTitle: 'Instructional Gesture',
      tamilName: 'உபதேச முத்திரை',
      virtueIds: '[43,44,24]',
      virtueWeights: '[58,71,68]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Nāda',
      domain: 'Soul',
      multiplier: 2.20,
      karmaPoints: 440,
      dutyType: 'Emotional',
      lifeStage: 'Elder',
      description: 'Teaching gestures and symbolic communication'
    },
    {
      artId: 61,
      artTitle: 'Prayer Symbol Design',
      tamilName: 'சுப சின்ன வடிவமைப்பு',
      virtueIds: '[46,44,39]',
      virtueWeights: '[82,71,76]',
      frequency: 'Monthly',
      frequencyBonus: 10,
      cosmicLayer: 'Jyoti',
      domain: 'Spirit',
      multiplier: 1.90,
      karmaPoints: 456,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Designing symbols for prayer and meditation'
    },
    {
      artId: 62,
      artTitle: 'Scripture Vessel Design',
      tamilName: 'சித்திரப் பொருள்',
      virtueIds: '[48,44,50]',
      virtueWeights: '[76,71,34]',
      frequency: 'Quarterly',
      frequencyBonus: 15,
      cosmicLayer: 'Rūpa',
      domain: 'Mixed',
      multiplier: 1.60,
      karmaPoints: 312,
      dutyType: 'Logistical',
      lifeStage: 'All',
      description: 'Designing containers for sacred texts'
    },
    {
      artId: 63,
      artTitle: 'Philosophical Offering',
      tamilName: 'பரிசேவை',
      virtueIds: '[24,22,36]',
      virtueWeights: '[68,91,16]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 288,
      dutyType: 'Emotional',
      lifeStage: 'All',
      description: 'Offerings based on philosophical understanding'
    },
    {
      artId: 64,
      artTitle: 'Sacred Gesture',
      tamilName: 'முத்திரை கலை',
      virtueIds: '[28,44,39]',
      virtueWeights: '[25,71,76]',
      frequency: 'Weekly',
      frequencyBonus: 5,
      cosmicLayer: 'Bhava',
      domain: 'Mind',
      multiplier: 1.60,
      karmaPoints: 268,
      dutyType: 'Ritual',
      lifeStage: 'All',
      description: 'Sacred hand gestures and mudras'
    }
  ];

  for (const artForm of artForms) {
    await prisma.artForm.upsert({
      where: { artId: artForm.artId },
      update: {
        ...artForm,
        roleTags: roleTagsMap[artForm.artId]
      },
      create: {
        ...artForm,
        roleTags: roleTagsMap[artForm.artId],
        learningDutyId: learningDuty.id
      }
    });
  }

  console.log('Art forms seeded successfully');
}